name: Bug report
description: Something isn't working as expected
title: 'bug: '
labels:
    - bug

body:
    - type: textarea
      id: bug_description
      attributes:
          label: What happened?
          description: Describe the unexpected behavior.
          placeholder: Describe the unexpected behavior.
      validations:
          required: true

    - type: textarea
      id: expected_behavior
      attributes:
          label: What did you expect?
          description: Describe what you expected to happen.
          placeholder: Describe what you expected to happen.
      validations:
          required: true

    - type: textarea
      id: reproduction_steps
      attributes:
          label: 'Short code snippet to reproduce the issue'
          description: Provide a short code snippet that reproduces the issue. Make sure to include all necessary imports and setup.
          render: typescript
      validations:
          required: true

    - type: input
      id: library_version
      attributes:
          label: 'Library version'
          description: Specify the version of the library you are using.
          placeholder: '1.0.0'
      validations:
          required: true

    - type: input
      id: node_version
      attributes:
          label: 'Node.js version'
          description: '`node -v` - Specify the version of Node.js you are using.'
          placeholder: '1.0.0'
      validations:
          required: true

    - type: input
      id: typescript_version
      attributes:
          label: 'TypeScript version'
          description: '`tsc -v` - Specify the version of TypeScript you are using.'
          placeholder: '1.0.0'
      validations:
          required: true

    - type: input
      id: bun_version
      attributes:
          label: 'Bun version'
          description: '`bun -v` - Specify the version of Bun you are using.'
          placeholder: '1.0.0'
